import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/ui/NavBar";

import { Montserrat } from "next/font/google";

// Configure Montserrat – adjust weights or subsets as necessary
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This layout is used for all pages in the app
// It wraps the entire application and provides a consistent layout
// across all pages. It includes the global styles and font settings.
// app/layout.js
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <head>
        <title>My Ecommerce & Blog App</title>
      </head>
      <body>
          <Navbar />
          <main>{children}</main>
          <footer>
            <p>My Site Footer</p>
          </footer>
      </body>
    </html>
  );
}

